name: Bun CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
    - run: bun i
    - run: bun run build
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: artifact - ${{ matrix.os }}
        path: dist/
